/*****************************************************************************
* Model: dpp.qm
* File:  ./philo.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::philo.c} ............................................................*/
#include "qpn.h"  /* QP-nano port */
#include "bsp.h"  /* Board Support Package */
#include "dpp.h"  /* Application interface */

Q_DEFINE_THIS_MODULE("philo")

/* Active object class -----------------------------------------------------*/
/*${AOs::Philo} ............................................................*/
typedef struct Philo {
/* protected: */
    QMActive super;
} Philo;

/* protected: */
static QState Philo_initial(Philo * const me);
static QState Philo_thinking  (Philo * const me);
static QState Philo_thinking_e(Philo * const me);
static QState Philo_thinking_x(Philo * const me);
static QMState const Philo_thinking_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Philo_thinking),
    Q_ACTION_CAST(&Philo_thinking_e),
    Q_ACTION_CAST(&Philo_thinking_x),
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Philo_hungry  (Philo * const me);
static QState Philo_hungry_e(Philo * const me);
static QMState const Philo_hungry_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Philo_hungry),
    Q_ACTION_CAST(&Philo_hungry_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Philo_eating  (Philo * const me);
static QState Philo_eating_e(Philo * const me);
static QState Philo_eating_x(Philo * const me);
static QMState const Philo_eating_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Philo_eating),
    Q_ACTION_CAST(&Philo_eating_e),
    Q_ACTION_CAST(&Philo_eating_x),
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/* Global objects ----------------------------------------------------------*/
/*${AOs::AO_Philo0} ........................................................*/
struct Philo AO_Philo0;

/*${AOs::AO_Philo1} ........................................................*/
struct Philo AO_Philo1;

/*${AOs::AO_Philo2} ........................................................*/
struct Philo AO_Philo2;

/*${AOs::AO_Philo3} ........................................................*/
struct Philo AO_Philo3;

/*${AOs::AO_Philo4} ........................................................*/
struct Philo AO_Philo4;


/* Local objects -----------------------------------------------------------*/
#define THINK_TIME  \
    (QTimeEvtCtr)((BSP_random() % BSP_TICKS_PER_SEC) + (BSP_TICKS_PER_SEC/2U))
#define EAT_TIME    \
    (QTimeEvtCtr)((BSP_random() % BSP_TICKS_PER_SEC) + BSP_TICKS_PER_SEC)

/* Philo definition --------------------------------------------------------*/
/*${AOs::Philo_ctor} .......................................................*/
void Philo_ctor(void) {
    QMActive_ctor(&AO_Philo0.super, Q_STATE_CAST(&Philo_initial));
    QMActive_ctor(&AO_Philo1.super, Q_STATE_CAST(&Philo_initial));
    QMActive_ctor(&AO_Philo2.super, Q_STATE_CAST(&Philo_initial));
    QMActive_ctor(&AO_Philo3.super, Q_STATE_CAST(&Philo_initial));
    QMActive_ctor(&AO_Philo4.super, Q_STATE_CAST(&Philo_initial));
    BSP_randomSeed(123U);
}
/*${AOs::Philo} ............................................................*/
/*${AOs::Philo::SM} ........................................................*/
static QState Philo_initial(Philo * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* transition-action table */
        &Philo_thinking_s, /* target state */
        {
            Q_ACTION_CAST(&Philo_thinking_e), /* entry */
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::Philo::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::Philo::SM::thinking} ..............................................*/
/* ${AOs::Philo::SM::thinking} */
static QState Philo_thinking_e(Philo * const me) {
    QActive_armX(&me->super, 0U, THINK_TIME, 0U);
    return QM_ENTRY(&Philo_thinking_s);
}
/* ${AOs::Philo::SM::thinking} */
static QState Philo_thinking_x(Philo * const me) {
    QActive_disarmX(&me->super, 0U);
    return QM_EXIT(&Philo_thinking_s);
}
/* ${AOs::Philo::SM::thinking} */
static QState Philo_thinking(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Philo::SM::thinking::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* transition-action table */
                &Philo_hungry_s, /* target state */
                {
                    Q_ACTION_CAST(&Philo_thinking_x), /* exit */
                    Q_ACTION_CAST(&Philo_hungry_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /* ${AOs::Philo::SM::thinking::EAT, DONE} */
        case EAT_SIG: /* intentionally fall through */
        case DONE_SIG: {
            Q_ERROR(); /* these events should never arrive in this state */
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return status_;
}
/*${AOs::Philo::SM::hungry} ................................................*/
/* ${AOs::Philo::SM::hungry} */
static QState Philo_hungry_e(Philo * const me) {
    QACTIVE_POST(&AO_Table, HUNGRY_SIG, me->super.prio);
    return QM_ENTRY(&Philo_hungry_s);
}
/* ${AOs::Philo::SM::hungry} */
static QState Philo_hungry(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Philo::SM::hungry::EAT} */
        case EAT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &Philo_eating_s, /* target state */
                {
                    Q_ACTION_CAST(&Philo_eating_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /* ${AOs::Philo::SM::hungry::DONE} */
        case DONE_SIG: {
            Q_ERROR(); /* this event should never arrive in this state */
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return status_;
}
/*${AOs::Philo::SM::eating} ................................................*/
/* ${AOs::Philo::SM::eating} */
static QState Philo_eating_e(Philo * const me) {
    QActive_armX(&me->super, 0U, EAT_TIME, 0U);
    return QM_ENTRY(&Philo_eating_s);
}
/* ${AOs::Philo::SM::eating} */
static QState Philo_eating_x(Philo * const me) {
    QActive_disarmX(&me->super, 0U);
    QACTIVE_POST(QF_ACTIVE_CAST(&AO_Table), DONE_SIG, me->super.prio);
    return QM_EXIT(&Philo_eating_s);
}
/* ${AOs::Philo::SM::eating} */
static QState Philo_eating(Philo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Philo::SM::eating::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* transition-action table */
                &Philo_thinking_s, /* target state */
                {
                    Q_ACTION_CAST(&Philo_eating_x), /* exit */
                    Q_ACTION_CAST(&Philo_thinking_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /* ${AOs::Philo::SM::eating::EAT, DONE} */
        case EAT_SIG: /* intentionally fall through */
        case DONE_SIG: {
            Q_ERROR(); /* these events should never arrive in this state */
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return status_;
}

