/*****************************************************************************
* Model: pelican.qm
* File:  ./ped.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "qpn_port.h"
#include "bsp.h"
#include "pelican.h"

/*Q_DEFINE_THIS_FILE*/

enum PedTimeouts {                             /* various timeouts in ticks */
    N_ATTEMPTS = 10,                      /* number of PED_WAITING attempts */
    WAIT_TOUT = BSP_TICKS_PER_SEC * 3,  /* wait between posting PED_WAITING */
    OFF_TOUT  = BSP_TICKS_PER_SEC * 8    /* wait time after posting OFF_SIG */
};

/* Peld class declaration --------------------------------------------------*/
/* @(/1/1) .................................................................*/
typedef struct PedTag {
/* protected: */
    QActive super;

/* private: */
    uint8_t retryCtr;
} Ped;

/* public: */
/** 
* constructor
*/
void Ped_ctor(void);

/* protected: */
QState Ped_initial(Ped *me);
QState Ped_off(Ped *me);
QState Ped_wait(Ped *me);


/* Global objects ----------------------------------------------------------*/
Ped AO_Ped;                 /* the single instance of the Ped active object */

/* Pelican class definition ------------------------------------------------*/
/* @(/1/1) .................................................................*/
/* @(/1/1/1) ...............................................................*/
void Ped_ctor(void) {
    QActive_ctor((QActive *)&AO_Ped, (QStateHandler)&Ped_initial);
}
/* @(/1/1/2) ...............................................................*/
/* @(/1/1/2/0) */
QState Ped_initial(Ped *me) {
    return Q_TRAN(&Ped_off);
}
/* @(/1/1/2/1) .............................................................*/
QState Ped_off(Ped *me) {
    switch (Q_SIG(me)) {
        /* @(/1/1/2/1) */
        case Q_ENTRY_SIG: {
            BSP_showState("off");
            QActive_arm((QActive *)me, OFF_TOUT);
            QActive_post((QActive *)&AO_Pelican, OFF_SIG, 0);
            return Q_HANDLED();
        }
        /* @(/1/1/2/1) */
        case Q_EXIT_SIG: {
            QActive_post((QActive *)&AO_Pelican, ON_SIG, 0);
            return Q_HANDLED();
        }
        /* @(/1/1/2/1/0) */
        case Q_TIMEOUT_SIG: {
            me->retryCtr = N_ATTEMPTS;
            return Q_TRAN(&Ped_wait);
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* @(/1/1/2/2) .............................................................*/
QState Ped_wait(Ped *me) {
    switch (Q_SIG(me)) {
        /* @(/1/1/2/2) */
        case Q_ENTRY_SIG: {
            BSP_showState("wait");
            QActive_post((QActive *)&AO_Pelican, PEDS_WAITING_SIG, 0);
            QActive_arm((QActive *)me, WAIT_TOUT);
            return Q_HANDLED();
        }
        /* @(/1/1/2/2/0) */
        case Q_TIMEOUT_SIG: {
            --me->retryCtr;
            /* @(/1/1/2/2/0/0) */
            if (me->retryCtr > 0) {
                return Q_TRAN(&Ped_wait);
            }
            /* @(/1/1/2/2/0/1) */
            else {
                return Q_TRAN(&Ped_off);
            }
        }
    }
    return Q_SUPER(&QHsm_top);
}

