/*****************************************************************************
* Model: game.qm
* File:  ./mine2.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "qpn_port.h"
#include "bsp.h"
#include "game.h"

Q_DEFINE_THIS_MODULE("mine2")

/* encapsulated delcaration of the Mine2 HSM -------------------------------*/
/* @(/1/4) .................................................................*/
/** 
* The Mine2 orthogonal component
*/
typedef struct Mine2Tag {
/* protected: */
    QHsm super;

/* private: */
    uint8_t x;
    uint8_t y;
    uint8_t exp_ctr;
} Mine2;

/* protected: */
static QState Mine2_initial(Mine2 * const me);
static QState Mine2_unused(Mine2 * const me);
static QState Mine2_used(Mine2 * const me);
static QState Mine2_planted(Mine2 * const me);
static QState Mine2_exploding(Mine2 * const me);


/* local objects -----------------------------------------------------------*/
static Mine2 l_mine2[GAME_MINES_MAX];             /* a pool of type-2 mines */

                             /* helper macro to provide the ID of this mine */
#define MINE_ID(me_)    ((me_) - l_mine2)

/* Mine2 class definition --------------------------------------------------*/
/* @(/1/13) ................................................................*/
QHsm * Mine2_ctor(uint8_t id) {
    Mine2 *me;
    Q_REQUIRE(id < GAME_MINES_MAX);

    me = &l_mine2[id];
    QHsm_ctor(&me->super, (QStateHandler)&Mine2_initial);
    return (QHsm *)me;
}
/* @(/1/4) .................................................................*/
/* @(/1/4/3) ...............................................................*/
/* @(/1/4/3/0) */
static QState Mine2_initial(Mine2 * const me) {
    return Q_TRAN(&Mine2_unused);
}
/* @(/1/4/3/1) .............................................................*/
static QState Mine2_unused(Mine2 * const me) {
    QState status;
    switch (Q_SIG(me)) {
        /* @(/1/4/3/1/0) */
        case MINE_PLANT_SIG: {
            me->x = (uint8_t)Q_PAR(me);
            me->y = (uint8_t)(Q_PAR(me) >> 8);
            status = Q_TRAN(&Mine2_planted);
            break;
        }
        default: {
            status = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status;
}
/* @(/1/4/3/2) .............................................................*/
static QState Mine2_used(Mine2 * const me) {
    QState status;
    switch (Q_SIG(me)) {
        /* @(/1/4/3/2) */
        case Q_EXIT_SIG: {
            /* tell the Tunnel that this mine is becoming disabled */
            QActive_post((QActive *)&AO_Tunnel,
                         MINE_DISABLED_SIG, MINE_ID(me));
            status = Q_HANDLED();
            break;
        }
        /* @(/1/4/3/2/0) */
        case MINE_RECYCLE_SIG: {
            status = Q_TRAN(&Mine2_unused);
            break;
        }
        default: {
            status = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status;
}
/* @(/1/4/3/2/1) ...........................................................*/
static QState Mine2_planted(Mine2 * const me) {
    QState status;
    switch (Q_SIG(me)) {
        /* @(/1/4/3/2/1/0) */
        case TIME_TICK_SIG: {
            /* @(/1/4/3/2/1/0/0) */
            if (me->x >= GAME_SPEED_X) {
                me->x -= GAME_SPEED_X;              /* move the mine 1 step */

                /* tell the Tunnel to draw the Mine */
                QActive_post((QActive *)&AO_Tunnel, MINE_IMG_SIG,
                             ((QParam)MINE2_BMP << 16)
                             | (QParam)me->x
                             | ((QParam)me->y << 8));
                status = Q_HANDLED();
            }
            /* @(/1/4/3/2/1/0/1) */
            else {
                status = Q_TRAN(&Mine2_unused);
            }
            break;
        }
        /* @(/1/4/3/2/1/1) */
        case SHIP_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* @(/1/4/3/2/1/1/0) */
            if (do_bitmaps_overlap(MINE2_BMP, me->x, me->y, bmp, x, y)) {
                QActive_post((QActive *)&AO_Ship, HIT_MINE_SIG,  2);
                /* go straight to 'disabled' and let the Ship do the exploding */
                status = Q_TRAN(&Mine2_unused);
            }
            else {
                status = Q_UNHANDLED();
            }
            break;
        }
        /* @(/1/4/3/2/1/2) */
        case MISSILE_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* @(/1/4/3/2/1/2/0) */
            if (do_bitmaps_overlap(MINE2_MISSILE_BMP, me->x, me->y, bmp, x, y)) {
                /* NOTE: Mine type-2 is nastier than Mine type-1.
                * The type-2 mine can hit the Ship with any of its
                * "tentacles". However, it can be destroyed by the
                * Missile only by hitting its center, defined as
                * a smaller bitmap MINE2_MISSILE_BMP.
                */
                /* post the score for destroying Mine type-2 */
                QActive_post((QActive *)&AO_Missile, DESTROYED_MINE_SIG, 45);
                status = Q_TRAN(&Mine2_exploding);
            }
            else {
                status = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status = Q_SUPER(&Mine2_used);
            break;
        }
    }
    return status;
}
/* @(/1/4/3/2/2) ...........................................................*/
static QState Mine2_exploding(Mine2 * const me) {
    QState status;
    switch (Q_SIG(me)) {
        /* @(/1/4/3/2/2) */
        case Q_ENTRY_SIG: {
            me->exp_ctr = 0;
            status = Q_HANDLED();
            break;
        }
        /* @(/1/4/3/2/2/0) */
        case TIME_TICK_SIG: {
            /* @(/1/4/3/2/2/0/0) */
            if ((me->x >= GAME_SPEED_X) && (me->exp_ctr < 15)) {
                ++me->exp_ctr; /* advance the explosion counter */
                me->x -= GAME_SPEED_X; /* move explosion by 1 step */

                /* tell the Game to render the current stage of Explosion */
                QActive_post((QActive *)&AO_Tunnel, EXPLOSION_SIG,
                         ((QParam)(EXPLOSION0_BMP + (me->exp_ctr >> 2)) << 16)
                         | ((QParam)(me->x + 1))
                         | (((QParam)((int)me->y - 4 + 2)) << 8));
                status = Q_HANDLED();
            }
            /* @(/1/4/3/2/2/0/1) */
            else {
                status = Q_TRAN(&Mine2_unused);
            }
            break;
        }
        default: {
            status = Q_SUPER(&Mine2_used);
            break;
        }
    }
    return status;
}

