/*****************************************************************************
* Model: game.qm
* File:  ./mine1.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::mine1.c} ............................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "game.h"

Q_DEFINE_THIS_MODULE("mine1")

/* encapsulated delcaration of the Mine1 HSM -------------------------------*/
/*${AOs::Mine1} ............................................................*/
typedef struct Mine1 {
/* protected: */
    QMsm super;

/* private: */
    uint8_t x;
    uint8_t y;
    uint8_t exp_ctr;
} Mine1;

/* protected: */
static QState Mine1_initial(Mine1 * const me);
static QState Mine1_unused  (Mine1 * const me);
static QMState const Mine1_unused_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Mine1_unused),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Mine1_used  (Mine1 * const me);
static QState Mine1_used_x(Mine1 * const me);
static QMState const Mine1_used_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Mine1_used),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(&Mine1_used_x),
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Mine1_planted  (Mine1 * const me);
static QMState const Mine1_planted_s = {
    &Mine1_used_s, /* superstate */
    Q_STATE_CAST(&Mine1_planted),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Mine1_exploding  (Mine1 * const me);
static QState Mine1_exploding_e(Mine1 * const me);
static QMState const Mine1_exploding_s = {
    &Mine1_used_s, /* superstate */
    Q_STATE_CAST(&Mine1_exploding),
    Q_ACTION_CAST(&Mine1_exploding_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/* local objects -----------------------------------------------------------*/
static Mine1 l_mine1[GAME_MINES_MAX];             /* a pool of type-1 mines */

                             /* helper macro to provide the ID of this mine */
#define MINE_ID(me_)    ((me_) - l_mine1)

/* Mine1 class definition --------------------------------------------------*/
/*${AOs::Mine1_ctor} .......................................................*/
QMsm * Mine1_ctor(uint8_t id) {
    Mine1 *me;
    Q_REQUIRE(id < GAME_MINES_MAX);

    me = &l_mine1[id];
    QMsm_ctor(&me->super, Q_STATE_CAST(&Mine1_initial));
    return (QMsm *)me;
}
/*${AOs::Mine1} ............................................................*/
/*${AOs::Mine1::SM} ........................................................*/
static QState Mine1_initial(Mine1 * const me) {
    static QMTranActTable const tatbl_ = { /* transition-action table */
        &Mine1_unused_s,
        {
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::Mine1::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::Mine1::SM::unused} ................................................*/
/* ${AOs::Mine1::SM::unused} */
static QState Mine1_unused(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Mine1::SM::unused::MINE_PLANT} */
        case MINE_PLANT_SIG: {
            static QMTranActTable const tatbl_ = { /* transition-action table */
                &Mine1_planted_s,
                {
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            me->x = (uint8_t)Q_PAR(me);
            me->y = (uint8_t)(Q_PAR(me) >> 8);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Mine1::SM::used} ..................................................*/
/* ${AOs::Mine1::SM::used} */
static QState Mine1_used_x(Mine1 * const me) {
    /* tell the Tunnel that this mine is becoming disabled */
    QACTIVE_POST((QActive *)&AO_Tunnel,
                 MINE_DISABLED_SIG, MINE_ID(me));
    return QM_EXIT(&Mine1_used_s);
}
/* ${AOs::Mine1::SM::used} */
static QState Mine1_used(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Mine1::SM::used::MINE_RECYCLE} */
        case MINE_RECYCLE_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &Mine1_unused_s, /* target state */
                {
                    Q_ACTION_CAST(&Mine1_used_x), /* exit */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Mine1::SM::used::planted} .........................................*/
/* ${AOs::Mine1::SM::used::planted} */
static QState Mine1_planted(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Mine1::SM::used::planted::TIME_TICK} */
        case TIME_TICK_SIG: {
            /* ${AOs::Mine1::SM::used::planted::TIME_TICK::[me->x>=GAME_S~]} */
            if (me->x >= GAME_SPEED_X) {
                me->x -= GAME_SPEED_X;  /* move the mine 1 step */

                /* tell the Tunnel to draw the Mine */
                QACTIVE_POST((QActive *)&AO_Tunnel, MINE_IMG_SIG,
                             ((QParam)MINE1_BMP << 16)
                             | (QParam)me->x
                             | ((QParam)me->y << 8));

                status_ = QM_HANDLED();
            }
            /* ${AOs::Mine1::SM::used::planted::TIME_TICK::[else]} */
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* transition-action table */
                    &Mine1_unused_s, /* target state */
                    {
                        Q_ACTION_CAST(&Mine1_used_x), /* exit */
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        /* ${AOs::Mine1::SM::used::planted::SHIP_IMG} */
        case SHIP_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* ${AOs::Mine1::SM::used::planted::SHIP_IMG::[do_bitmaps_ov~]} */
            if (do_bitmaps_overlap(MINE1_BMP, me->x, me->y, bmp, x, y)) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* transition-action table */
                    &Mine1_unused_s, /* target state */
                    {
                        Q_ACTION_CAST(&Mine1_used_x), /* exit */
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                QACTIVE_POST((QActive *)&AO_Ship, HIT_MINE_SIG,  1);

                /* go straight to 'disabled' and let the Ship do
                * the exploding
                */
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        /* ${AOs::Mine1::SM::used::planted::MISSILE_IMG} */
        case MISSILE_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* ${AOs::Mine1::SM::used::planted::MISSILE_IMG::[do_bitmaps_ov~]} */
            if (do_bitmaps_overlap(MINE1_BMP, me->x, me->y, bmp, x, y)) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* transition-action table */
                    &Mine1_exploding_s, /* target state */
                    {
                        Q_ACTION_CAST(&Mine1_exploding_e), /* entry */
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                /* post the score for destroying Mine type-1 */
                QACTIVE_POST((QActive *)&AO_Missile, DESTROYED_MINE_SIG, 25);
                status_ = QM_TRAN(&tatbl_);
            }
            else {
                status_ = QM_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Mine1::SM::used::exploding} .......................................*/
/* ${AOs::Mine1::SM::used::exploding} */
static QState Mine1_exploding_e(Mine1 * const me) {
    me->exp_ctr = 0;
    return QM_ENTRY(&Mine1_exploding_s);
}
/* ${AOs::Mine1::SM::used::exploding} */
static QState Mine1_exploding(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Mine1::SM::used::exploding::TIME_TICK} */
        case TIME_TICK_SIG: {
            /* ${AOs::Mine1::SM::used::exploding::TIME_TICK::[(me->x>=GAME_~]} */
            if ((me->x >= GAME_SPEED_X) && (me->exp_ctr < 15)) {
                ++me->exp_ctr;  /* advance the explosion counter */
                me->x -= GAME_SPEED_X; /* move explosion by 1 step */

                /* tell the Game to render the current stage of Explosion */
                QACTIVE_POST((QActive *)&AO_Tunnel, EXPLOSION_SIG,
                         ((QParam)(EXPLOSION0_BMP + (me->exp_ctr >> 2)) << 16)
                         | ((QParam)(me->x + 1))
                         | (((QParam)((int)me->y - 4 + 2)) << 8));
                status_ = QM_HANDLED();
            }
            /* ${AOs::Mine1::SM::used::exploding::TIME_TICK::[else]} */
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* transition-action table */
                    &Mine1_unused_s, /* target state */
                    {
                        Q_ACTION_CAST(&Mine1_used_x), /* exit */
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

