/*****************************************************************************
* Model: game.qm
* File:  ./mine1.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/4) .................................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "game.h"

Q_DEFINE_THIS_MODULE("mine1")

/* encapsulated delcaration of the Mine1 HSM -------------------------------*/
/* @(/1/3) .................................................................*/
typedef struct Mine1Tag {
/* protected: */
    QHsm super;

/* private: */
    uint8_t x;
    uint8_t y;
    uint8_t exp_ctr;
} Mine1;

/* protected: */
static QState Mine1_initial(Mine1 * const me);
static QState Mine1_unused(Mine1 * const me);
static QState Mine1_used(Mine1 * const me);
static QState Mine1_planted(Mine1 * const me);
static QState Mine1_exploding(Mine1 * const me);


/* local objects -----------------------------------------------------------*/
static Mine1 l_mine1[GAME_MINES_MAX];             /* a pool of type-1 mines */

                             /* helper macro to provide the ID of this mine */
#define MINE_ID(me_)    ((me_) - l_mine1)

/* Mine1 class definition --------------------------------------------------*/
/* @(/1/12) ................................................................*/
QHsm * Mine1_ctor(uint8_t id) {
    Mine1 *me;
    Q_REQUIRE(id < GAME_MINES_MAX);

    me = &l_mine1[id];
    QHsm_ctor(&me->super, (QStateHandler)&Mine1_initial);
    return (QHsm *)me;
}
/* @(/1/3) .................................................................*/
/* @(/1/3/3) ...............................................................*/
/* @(/1/3/3/0) */
static QState Mine1_initial(Mine1 * const me) {
    return Q_TRAN(&Mine1_unused);
}
/* @(/1/3/3/1) .............................................................*/
static QState Mine1_unused(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/3/3/1/0) */
        case MINE_PLANT_SIG: {
            me->x = (uint8_t)Q_PAR(me);
            me->y = (uint8_t)(Q_PAR(me) >> 8);
            status_ = Q_TRAN(&Mine1_planted);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/3/3/2) .............................................................*/
static QState Mine1_used(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/3/3/2) */
        case Q_EXIT_SIG: {
            /* tell the Tunnel that this mine is becoming disabled */
            QACTIVE_POST((QActive *)&AO_Tunnel,
                         MINE_DISABLED_SIG, MINE_ID(me));
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/3/3/2/0) */
        case MINE_RECYCLE_SIG: {
            status_ = Q_TRAN(&Mine1_unused);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/3/3/2/1) ...........................................................*/
static QState Mine1_planted(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/3/3/2/1/0) */
        case TIME_TICK_SIG: {
            /* @(/1/3/3/2/1/0/0) */
            if (me->x >= GAME_SPEED_X) {
                me->x -= GAME_SPEED_X;  /* move the mine 1 step */

                /* tell the Tunnel to draw the Mine */
                QACTIVE_POST((QActive *)&AO_Tunnel, MINE_IMG_SIG,
                             ((QParam)MINE1_BMP << 16)
                             | (QParam)me->x
                             | ((QParam)me->y << 8));

                status_ = Q_HANDLED();
            }
            /* @(/1/3/3/2/1/0/1) */
            else {
                status_ = Q_TRAN(&Mine1_unused);
            }
            break;
        }
        /* @(/1/3/3/2/1/1) */
        case SHIP_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* @(/1/3/3/2/1/1/0) */
            if (do_bitmaps_overlap(MINE1_BMP, me->x, me->y, bmp, x, y)) {
                QACTIVE_POST((QActive *)&AO_Ship, HIT_MINE_SIG,  1);

                /* go straight to 'disabled' and let the Ship do
                * the exploding
                */
                status_ = Q_TRAN(&Mine1_unused);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /* @(/1/3/3/2/1/2) */
        case MISSILE_IMG_SIG: {
            uint8_t x   = (uint8_t)Q_PAR(me);
            uint8_t y   = (uint8_t)(Q_PAR(me) >> 8);
            uint8_t bmp = (uint8_t)(Q_PAR(me) >> 16);
            /* @(/1/3/3/2/1/2/0) */
            if (do_bitmaps_overlap(MINE1_BMP, me->x, me->y, bmp, x, y)) {
                /* post the score for destroying Mine type-1 */
                QACTIVE_POST((QActive *)&AO_Missile, DESTROYED_MINE_SIG, 25);
                status_ = Q_TRAN(&Mine1_exploding);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Mine1_used);
            break;
        }
    }
    return status_;
}
/* @(/1/3/3/2/2) ...........................................................*/
static QState Mine1_exploding(Mine1 * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/3/3/2/2) */
        case Q_ENTRY_SIG: {
            me->exp_ctr = 0;
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/3/3/2/2/0) */
        case TIME_TICK_SIG: {
            /* @(/1/3/3/2/2/0/0) */
            if ((me->x >= GAME_SPEED_X) && (me->exp_ctr < 15)) {
                ++me->exp_ctr;  /* advance the explosion counter */
                me->x -= GAME_SPEED_X; /* move explosion by 1 step */

                /* tell the Game to render the current stage of Explosion */
                QACTIVE_POST((QActive *)&AO_Tunnel, EXPLOSION_SIG,
                         ((QParam)(EXPLOSION0_BMP + (me->exp_ctr >> 2)) << 16)
                         | ((QParam)(me->x + 1))
                         | (((QParam)((int)me->y - 4 + 2)) << 8));
                status_ = Q_HANDLED();
            }
            /* @(/1/3/3/2/2/0/1) */
            else {
                status_ = Q_TRAN(&Mine1_unused);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Mine1_used);
            break;
        }
    }
    return status_;
}

