/*****************************************************************************
* Model: pelican.qm
* File:  ./pelican.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#ifndef pelican_h
#define pelican_h

enum PelicanSignals {
    PEDS_WAITING_SIG = Q_USER_SIG,
    OFF_SIG,
    ON_SIG,
    TEST_SIG
};

/* active objects ................................................*/
#ifndef AO_PELICAN
extern QActive AO_Pelican;
#endif
#ifndef AO_PED
extern QActive AO_Ped;
#endif

/** 
* constructor
*/
void Pelican_ctor(void);

/** 
* constructor
*/
void Ped_ctor(void);


#endif /* pelican_h */
