/*****************************************************************************
* Model: pelican.qm
* File:  ./pelican.c
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#include "qpn_port.h"
#include "bsp.h"

#define AO_PELICAN
#include "pelican.h"

/*Q_DEFINE_THIS_FILE*/

enum PelicanTimeouts {  /* various timeouts in ticks */
    CARS_GREEN_MIN_TOUT = BSP_TICKS_PER_SEC * 8, /* min green for cars */
    CARS_YELLOW_TOUT = BSP_TICKS_PER_SEC * 3,  /* yellow for cars */
    PEDS_WALK_TOUT   = BSP_TICKS_PER_SEC * 3,  /* walking time for peds */
    PEDS_FLASH_TOUT  = BSP_TICKS_PER_SEC / 5,  /* flashing timeout for peds */
    PEDS_FLASH_NUM   = 5*2,                    /* number of flashes for peds */
    OFF_FLASH_TOUT   = BSP_TICKS_PER_SEC / 2   /* flashing timeout when off */
};

/* Pelican class declaration -----------------------------------------------*/
/* @(/1/0) .................................................................*/
/** 
* PEdestrian LIght CONtrolled (PELICAN) crossing
*/
typedef struct PelicanTag {
/* protected: */
    QActive super;

/* private: */
    uint8_t flashCtr;
} Pelican;

/* public: */
/** 
* constructor
*/
void Pelican_ctor(void);

/* protected: */
QState Pelican_initial(Pelican *me);
QState Pelican_operational(Pelican *me);
QState Pelican_carsEnabled(Pelican *me);
QState Pelican_carsGreen(Pelican *me);
QState Pelican_carsGreenNoPed(Pelican *me);
QState Pelican_carsGreenInt(Pelican *me);
QState Pelican_carsGreenPedWait(Pelican *me);
QState Pelican_carsYellow(Pelican *me);
QState Pelican_pedsEnabled(Pelican *me);
QState Pelican_pedsWalk(Pelican *me);
QState Pelican_pedsFlash(Pelican *me);
QState Pelican_offline(Pelican *me);


/* Global objects ----------------------------------------------------------*/
Pelican AO_Pelican;     /* the single instance of the Pelican active object */

/* Pelican class definition ------------------------------------------------*/
/* @(/1/0) .................................................................*/
/* @(/1/0/1) ...............................................................*/
void Pelican_ctor(void) {
    QActive_ctor((QActive *)&AO_Pelican, (QStateHandler)&Pelican_initial);
}
/* @(/1/0/2) ...............................................................*/
/* @(/1/0/2/0) */
QState Pelican_initial(Pelican *me) {
    return Q_TRAN(&Pelican_operational);
}
/* @(/1/0/2/1) .............................................................*/
QState Pelican_operational(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1) */
        case Q_ENTRY_SIG: {
            BSP_signalCars(CARS_RED);
            BSP_signalPeds(PEDS_DONT_WALK);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/0) */
        case Q_INIT_SIG: {
            return Q_TRAN(&Pelican_carsEnabled);
        }
        /* @(/1/0/2/1/1) */
        case OFF_SIG: {
            return Q_TRAN(&Pelican_offline);
        }
    }
    return Q_SUPER(&QHsm_top);
}
/* @(/1/0/2/1/2) ...........................................................*/
QState Pelican_carsEnabled(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2) */
        case Q_EXIT_SIG: {
            BSP_signalCars(CARS_RED);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/0) */
        case Q_INIT_SIG: {
            return Q_TRAN(&Pelican_carsGreen);
        }
    }
    return Q_SUPER(&Pelican_operational);
}
/* @(/1/0/2/1/2/1) .........................................................*/
QState Pelican_carsGreen(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2/1) */
        case Q_ENTRY_SIG: {
            BSP_signalCars(CARS_GREEN);
            QActive_arm((QActive *)me, CARS_GREEN_MIN_TOUT);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/1) */
        case Q_EXIT_SIG: {
            QActive_disarm((QActive *)me);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/1/0) */
        case Q_INIT_SIG: {
            return Q_TRAN(&Pelican_carsGreenNoPed);
        }
    }
    return Q_SUPER(&Pelican_carsEnabled);
}
/* @(/1/0/2/1/2/1/1) .......................................................*/
QState Pelican_carsGreenNoPed(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2/1/1) */
        case Q_ENTRY_SIG: {
            BSP_showState("carsGreenNoPed");
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/1/1/0) */
        case PEDS_WAITING_SIG: {
            return Q_TRAN(&Pelican_carsGreenPedWait);
        }
        /* @(/1/0/2/1/2/1/1/1) */
        case Q_TIMEOUT_SIG: {
            return Q_TRAN(&Pelican_carsGreenInt);
        }
    }
    return Q_SUPER(&Pelican_carsGreen);
}
/* @(/1/0/2/1/2/1/2) .......................................................*/
QState Pelican_carsGreenInt(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2/1/2) */
        case Q_ENTRY_SIG: {
            BSP_showState("carsGreenInt");
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/1/2/0) */
        case PEDS_WAITING_SIG: {
            return Q_TRAN(&Pelican_carsYellow);
        }
    }
    return Q_SUPER(&Pelican_carsGreen);
}
/* @(/1/0/2/1/2/1/3) .......................................................*/
QState Pelican_carsGreenPedWait(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2/1/3) */
        case Q_ENTRY_SIG: {
            BSP_showState("carsGreenPedWait");
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/1/3/0) */
        case Q_TIMEOUT_SIG: {
            return Q_TRAN(&Pelican_carsYellow);
        }
    }
    return Q_SUPER(&Pelican_carsGreen);
}
/* @(/1/0/2/1/2/2) .........................................................*/
QState Pelican_carsYellow(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/2/2) */
        case Q_ENTRY_SIG: {
            BSP_showState("carsYellow");
            BSP_signalCars(CARS_YELLOW);
            QActive_arm((QActive *)me, CARS_YELLOW_TOUT);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/2) */
        case Q_EXIT_SIG: {
            QActive_disarm((QActive *)me);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/2/2/0) */
        case Q_TIMEOUT_SIG: {
            return Q_TRAN(&Pelican_pedsEnabled);
        }
    }
    return Q_SUPER(&Pelican_carsEnabled);
}
/* @(/1/0/2/1/3) ...........................................................*/
QState Pelican_pedsEnabled(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/3) */
        case Q_EXIT_SIG: {
            BSP_signalPeds(PEDS_DONT_WALK);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/3/0) */
        case Q_INIT_SIG: {
            return Q_TRAN(&Pelican_pedsWalk);
        }
    }
    return Q_SUPER(&Pelican_operational);
}
/* @(/1/0/2/1/3/1) .........................................................*/
QState Pelican_pedsWalk(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/3/1) */
        case Q_ENTRY_SIG: {
            BSP_showState("pedsWalk");
            BSP_signalPeds(PEDS_WALK);
            QActive_arm((QActive *)me, PEDS_WALK_TOUT);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/3/1) */
        case Q_EXIT_SIG: {
            QActive_disarm((QActive *)me);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/3/1/0) */
        case Q_TIMEOUT_SIG: {
            return Q_TRAN(&Pelican_pedsFlash);
        }
    }
    return Q_SUPER(&Pelican_pedsEnabled);
}
/* @(/1/0/2/1/3/2) .........................................................*/
QState Pelican_pedsFlash(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/1/3/2) */
        case Q_ENTRY_SIG: {
            BSP_showState("pedsFlash");
            QActive_arm((QActive *)me, PEDS_FLASH_TOUT);
            me->flashCtr = PEDS_FLASH_NUM*2 + 1;
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/3/2) */
        case Q_EXIT_SIG: {
            QActive_disarm((QActive *)me);
            return Q_HANDLED();
        }
        /* @(/1/0/2/1/3/2/0) */
        case Q_TIMEOUT_SIG: {
            /* @(/1/0/2/1/3/2/0/0) */
            if (me->flashCtr != 0U) {
                --me->flashCtr;
                QActive_arm((QActive *)me, PEDS_FLASH_TOUT);
                /* @(/1/0/2/1/3/2/0/0/0) */
                if ((me->flashCtr & 1U) == 0U) {
                    BSP_signalPeds(PEDS_DONT_WALK);
                    return Q_HANDLED();
                }
                /* @(/1/0/2/1/3/2/0/0/1) */
                else {
                    BSP_signalPeds(PEDS_BLANK);
                    return Q_HANDLED();
                }
            }
            /* @(/1/0/2/1/3/2/0/1) */
            else {
                return Q_TRAN(&Pelican_carsEnabled);
            }
        }
    }
    return Q_SUPER(&Pelican_pedsEnabled);
}
/* @(/1/0/2/2) .............................................................*/
QState Pelican_offline(Pelican *me) {
    switch (Q_SIG(me)) {
        /* @(/1/0/2/2) */
        case Q_ENTRY_SIG: {
            BSP_showState("offline");
            QActive_arm((QActive *)me, OFF_FLASH_TOUT);
            me->flashCtr = 0;
            return Q_HANDLED();
        }
        /* @(/1/0/2/2) */
        case Q_EXIT_SIG: {
            QActive_disarm((QActive *)me);
            return Q_HANDLED();
        }
        /* @(/1/0/2/2/0) */
        case Q_TIMEOUT_SIG: {
            QActive_arm((QActive *)me, OFF_FLASH_TOUT);
            me->flashCtr ^= 1;
            /* @(/1/0/2/2/0/0) */
            if ((me->flashCtr & 1U) == 0U) {
                BSP_signalCars(CARS_RED);
                BSP_signalPeds(PEDS_DONT_WALK);
                return Q_HANDLED();
            }
            /* @(/1/0/2/2/0/1) */
            else {
                BSP_signalCars(CARS_BLANK);
                BSP_signalPeds(PEDS_BLANK);
                return Q_HANDLED();
            }
        }
        /* @(/1/0/2/2/1) */
        case ON_SIG: {
            return Q_TRAN(&Pelican_operational);
        }
    }
    return Q_SUPER(&QHsm_top);
}

