/*****************************************************************************
* Model: pelican.qm
* File:  ./ped.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::ped.c} ..............................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "pelican.h"

/*Q_DEFINE_THIS_FILE*/

/* Ped class declaration ---------------------------------------------------*/
/*${AOs::Ped} ..............................................................*/
typedef struct Ped {
/* protected: */
    QMActive super;

/* private: */
    uint8_t offCtr;
} Ped;

/* protected: */
static QState Ped_initial(Ped * const me);
static QState Ped_wait  (Ped * const me);
static QState Ped_wait_e(Ped * const me);
static QMState const Ped_wait_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Ped_wait),
    Q_ACTION_CAST(&Ped_wait_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/* Global objects ----------------------------------------------------------*/
Ped AO_Ped; /* the single instance of the Ped AO */

enum PedTimeouts {  /* various timeouts in ticks */
    N_ATTEMPTS = 10, /* number of PED_WAITING attempts before posting OFF_SIG */
    WAIT_TOUT  = BSP_TICKS_PER_SEC * 10 /* wait time after posting PEDS_WAITING_SIG */
};

/* Pelican class definition ------------------------------------------------*/
/*${AOs::Ped_ctor} .........................................................*/
void Ped_ctor(void) {
    QMActive_ctor(&AO_Ped.super, Q_STATE_CAST(&Ped_initial));
}
/*${AOs::Ped} ..............................................................*/
/*${AOs::Ped::SM} ..........................................................*/
static QState Ped_initial(Ped * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* transition-action table */
        &Ped_wait_s, /* target state */
        {
            Q_ACTION_CAST(&Ped_wait_e), /* entry */
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::Ped::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::Ped::SM::wait} ....................................................*/
/* ${AOs::Ped::SM::wait} */
static QState Ped_wait_e(Ped * const me) {
    me->offCtr = N_ATTEMPTS;
    QActive_armX(&me->super, 0U, WAIT_TOUT);
    QACTIVE_POST((QActive *)&AO_Pelican, ON_SIG);
    return QM_ENTRY(&Ped_wait_s);
}
/* ${AOs::Ped::SM::wait} */
static QState Ped_wait(Ped * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Ped::SM::wait::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            --me->offCtr;
            QActive_armX((QActive *)me, 0U, WAIT_TOUT);
            /* ${AOs::Ped::SM::wait::Q_TIMEOUT::[me->offCtr!=0U]} */
            if (me->offCtr != 0U) {
                QACTIVE_POST((QActive *)&AO_Pelican, PEDS_WAITING_SIG);
                status_ = QM_HANDLED();
            }
            /* ${AOs::Ped::SM::wait::Q_TIMEOUT::[else]} */
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* transition-action table */
                    &Ped_wait_s, /* target state */
                    {
                        Q_ACTION_CAST(&Ped_wait_e), /* entry */
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                QACTIVE_POST((QActive *)&AO_Pelican, OFF_SIG);
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

