/*****************************************************************************
* Model: game.qm
* File:  ./missile.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::missile.c} ..........................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "game.h"

/* Q_DEFINE_THIS_MODULE(missile) */

/* encapsulated delcaration of the Missile active object -------------------*/
/*${AOs::Missile} ..........................................................*/
typedef struct Missile {
/* protected: */
    QMActive super;

/* private: */
    uint8_t x;
    uint8_t y;
    uint8_t exp_ctr;

/* public: */
    uint8_t speed;
} Missile;

/* protected: */
static QState Missile_initial(Missile * const me);
static QState Missile_armed  (Missile * const me);
static QMState const Missile_armed_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Missile_armed),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Missile_flying  (Missile * const me);
static QMState const Missile_flying_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Missile_flying),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState Missile_exploding  (Missile * const me);
static QState Missile_exploding_e(Missile * const me);
static QMState const Missile_exploding_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&Missile_exploding),
    Q_ACTION_CAST(&Missile_exploding_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/* global objects ----------------------------------------------------------*/
Missile AO_Missile;

/* Active object definition ------------------------------------------------*/
/*${AOs::Missile_ctor} .....................................................*/
void Missile_ctor(uint8_t speed) {
    Missile *me = &AO_Missile;
    QMActive_ctor(&me->super, Q_STATE_CAST(&Missile_initial));
    me->speed = speed;
}
/*${AOs::Missile} ..........................................................*/
/*${AOs::Missile::SM} ......................................................*/
static QState Missile_initial(Missile * const me) {
    static QMTranActTable const tatbl_ = { /* transition-action table */
        &Missile_armed_s,
        {
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::Missile::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::Missile::SM::armed} ...............................................*/
/* ${AOs::Missile::SM::armed} */
static QState Missile_armed(Missile * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Missile::SM::armed::MISSILE_FIRE} */
        case MISSILE_FIRE_SIG: {
            static QMTranActTable const tatbl_ = { /* transition-action table */
                &Missile_flying_s,
                {
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            me->x = (uint8_t)Q_PAR(me); /* init position from the Ship */
            me->y = (uint8_t)(Q_PAR(me) >> 8);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Missile::SM::flying} ..............................................*/
/* ${AOs::Missile::SM::flying} */
static QState Missile_flying(Missile * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Missile::SM::flying::TIME_TICK} */
        case TIME_TICK_SIG: {
            /* ${AOs::Missile::SM::flying::TIME_TICK::[me->x+GAME_MI~]} */
            if (me->x + GAME_MISSILE_SPEED_X < GAME_SCREEN_WIDTH) {
                me->x += me->speed;
                /*tell the Tunnel to draw the Missile and test for wall hits*/
                QACTIVE_POST((QActive *)&AO_Tunnel, MISSILE_IMG_SIG,
                             ((QParam)MISSILE_BMP << 16)
                             | (QParam)me->x
                             | ((QParam)me->y << 8));
                status_ = QM_HANDLED();
            }
            /* ${AOs::Missile::SM::flying::TIME_TICK::[else]} */
            else {
                static QMTranActTable const tatbl_ = { /* transition-action table */
                    &Missile_armed_s,
                    {
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        /* ${AOs::Missile::SM::flying::HIT_WALL} */
        case HIT_WALL_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &Missile_exploding_s, /* target state */
                {
                    Q_ACTION_CAST(&Missile_exploding_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /* ${AOs::Missile::SM::flying::DESTROYED_MINE} */
        case DESTROYED_MINE_SIG: {
            static QMTranActTable const tatbl_ = { /* transition-action table */
                &Missile_armed_s,
                {
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            /* tell the Ship the score for destroing this Mine */
            QACTIVE_POST((QActive *)&AO_Ship, Q_SIG(me), Q_PAR(me));
            /* re-arm immediately & let the destroyed Mine do the exploding */
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${AOs::Missile::SM::exploding} ...........................................*/
/* ${AOs::Missile::SM::exploding} */
static QState Missile_exploding_e(Missile * const me) {
    me->exp_ctr = 0;
    return QM_ENTRY(&Missile_exploding_s);
}
/* ${AOs::Missile::SM::exploding} */
static QState Missile_exploding(Missile * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* ${AOs::Missile::SM::exploding::TIME_TICK} */
        case TIME_TICK_SIG: {
            /* ${AOs::Missile::SM::exploding::TIME_TICK::[(me->x>=GAME_~]} */
            if ((me->x >= GAME_SPEED_X) && (me->exp_ctr < 15)) {
                ++me->exp_ctr;             /* advance the explosion counter */
                me->x -= me->speed;       /* move the explosion by one step */

                /* tell the Tunnel to render the current stage of Explosion */
                QACTIVE_POST((QActive *)&AO_Tunnel, EXPLOSION_SIG,
                         ((QParam)(EXPLOSION0_BMP + (me->exp_ctr >> 2)) << 16)
                         | (QParam)(me->x + 3)
                         | ((QParam)((int)me->y - 4) << 8));
                status_ = QM_HANDLED();
            }
            /* ${AOs::Missile::SM::exploding::TIME_TICK::[else]} */
            else {
                static QMTranActTable const tatbl_ = { /* transition-action table */
                    &Missile_armed_s,
                    {
                        Q_ACTION_CAST(0) /* zero terminator */
                    }
                };
                /* explosion finished or moved outside the game */
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

