/*$file${.::dpp.h} #########################################################*/
/*
* Model: dpp.qm
* File:  ${.::dpp.h}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::dpp.h} ######################################################*/
#ifndef dpp_h
#define dpp_h

enum DPPSignals {
    EAT_SIG = Q_USER_SIG, /* published by Table to let a philosopher eat */
    DONE_SIG,             /* published by Philosopher when done eating */
    PAUSE_SIG,            /* published by BSP to pause the application */
    SERVE_SIG,            /* published by BSP to pause the application */
    TERMINATE_SIG,        /* published by BSP to terminate the application */
    HUNGRY_SIG,           /* posted direclty to Table from hungry Philo */
    MAX_SIG               /* the last signal */
};

/* number of philosophers */
#define N_PHILO ((uint8_t)5)
#define PHILO_0_PRIO 1

/*$declare${AOs::AO_Philo0} ################################################*/
extern struct Philo AO_Philo0;
/*$enddecl${AOs::AO_Philo0} ################################################*/
/*$declare${AOs::AO_Philo1} ################################################*/
extern struct Philo AO_Philo1;
/*$enddecl${AOs::AO_Philo1} ################################################*/
/*$declare${AOs::AO_Philo2} ################################################*/
extern struct Philo AO_Philo2;
/*$enddecl${AOs::AO_Philo2} ################################################*/
/*$declare${AOs::AO_Philo3} ################################################*/
extern struct Philo AO_Philo3;
/*$enddecl${AOs::AO_Philo3} ################################################*/
/*$declare${AOs::AO_Philo4} ################################################*/
extern struct Philo AO_Philo4;
/*$enddecl${AOs::AO_Philo4} ################################################*/
/*$declare${AOs::AO_Table} #################################################*/
extern struct Table AO_Table;
/*$enddecl${AOs::AO_Table} #################################################*/

/*$declare${AOs::Philo_ctor} ###############################################*/
/*${AOs::Philo_ctor} .......................................................*/
void Philo_ctor(void);
/*$enddecl${AOs::Philo_ctor} ###############################################*/
/*$declare${AOs::Table_ctor} ###############################################*/
/*${AOs::Table_ctor} .......................................................*/
void Table_ctor(void);
/*$enddecl${AOs::Table_ctor} ###############################################*/

#endif /* dpp_h */
