PROJNAME=pelican_psoceval1
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/software/qpn/examples/psoc/iccm8c/PELICA~1
PSOCDIR=C:/tools/Cypress/PSOC_D~1
INCLUDE_PATH=C:/tools/Cypress/PSOC_D~1/tools/include/CY8C29~1
CSRCS= bsp.c main.c oper.c pelican.c qepn.c qfn.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= led_1.asm led_2.asm led_3.asm led_4.asm psocconfig.asm psocconfigtbl.asm sleeptimer_1.asm sleeptimer_1int.asm uart_1.asm uart_1int.asm uart_1plus.asm
OBJECT_SOURCES= bsp.c main.c oper.c pelican.c qepn.c qfn.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=-elim:UserModules
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
CDEFINES= -DNDEBUG
LIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=pelican_psoceval1 
