/*****************************************************************************
* Model: game.qm
* File:  ./ship.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/2) .................................................................*/
#include "qpn_port.h"
#include "bsp.h"
#include "game.h"

/* Q_DEFINE_THIS_MODULE(ship) */

#define SHIP_WIDTH  5U
#define SHIP_HEIGHT 3U

/* encapsulated delcaration of the Ship active object ----------------------*/
/* @(/1/1) .................................................................*/
typedef struct ShipTag {
/* protected: */
    QMActive super;

/* private: */
    uint8_t x;
    uint8_t y;
    uint8_t exp_ctr;
    uint16_t score;
} Ship;

/* protected: */
static QState Ship_initial(Ship * const me);
static QState Ship_active  (Ship * const me);
static QState Ship_active_i(Ship * const me);
static QMState const Ship_active_s = {
    (QMState const *)0,
    Q_STATE_CAST(&Ship_active),
    Q_ACTION_CAST(0)
};
static QState Ship_parked  (Ship * const me);
static QMState const Ship_parked_s = {
    &Ship_active_s,
    Q_STATE_CAST(&Ship_parked),
    Q_ACTION_CAST(0)
};
static QState Ship_flying  (Ship * const me);
static QState Ship_flying_e(Ship * const me);
static QMState const Ship_flying_s = {
    &Ship_active_s,
    Q_STATE_CAST(&Ship_flying),
    Q_ACTION_CAST(0)
};
static QState Ship_exploding  (Ship * const me);
static QState Ship_exploding_e(Ship * const me);
static QMState const Ship_exploding_s = {
    &Ship_active_s,
    Q_STATE_CAST(&Ship_exploding),
    Q_ACTION_CAST(0)
};


/* global objects ----------------------------------------------------------*/
Ship AO_Ship;

/* Active object definition ------------------------------------------------*/
/* @(/1/10) ................................................................*/
void Ship_ctor(void) {
    Ship *me = &AO_Ship;
    QMActive_ctor(&me->super, Q_STATE_CAST(&Ship_initial));
    me->x = GAME_SHIP_X;
    me->y = GAME_SHIP_Y;
}
/* @(/1/1) .................................................................*/
/* @(/1/1/4) ...............................................................*/
/* @(/1/1/4/0) */
static QState Ship_initial(Ship * const me) {
    static QActionHandler const act_[] = {
        Q_ACTION_CAST(&Ship_active_i),
        Q_ACTION_CAST(0)
    };
    return QM_INITIAL(&Ship_active_s, &act_[0]);
}
/* @(/1/1/4/1) .............................................................*/
static QState Ship_active_i(Ship * const me) {
    return QM_INITIAL(&Ship_parked_s, QMsm_emptyAction_);
}
static QState Ship_active(Ship * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/1/4/1/1) */
        case PLAYER_SHIP_MOVE_SIG: {
            me->x = (uint8_t)Q_PAR(me);
            me->y = (uint8_t)(Q_PAR(me) >> 8);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/* @(/1/1/4/1/2) ...........................................................*/
static QState Ship_parked(Ship * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/1/4/1/2/0) */
        case TAKE_OFF_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Ship_flying_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Ship_flying_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/* @(/1/1/4/1/3) ...........................................................*/
static QState Ship_flying_e(Ship * const me) {
    me->score = 0; /* reset the score */
    QACTIVE_POST((QActive *)&AO_Tunnel, SCORE_SIG, me->score);
    return QM_ENTRY(&Ship_flying_s);
}
static QState Ship_flying(Ship * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/1/4/1/3/0) */
        case TIME_TICK_SIG: {
            /* tell the Tunnel to draw the Ship and test for hits */
            QACTIVE_POST((QActive *)&AO_Tunnel, SHIP_IMG_SIG,
                         ((QParam)SHIP_BMP << 16)
                         | (QParam)me->x
                         | ((QParam)me->y << 8));

            ++me->score;  /* increment the score for surviving another tick */

            if ((me->score % 10) == 0) { /* is the score "round"? */
                QACTIVE_POST((QActive *)&AO_Tunnel, SCORE_SIG, me->score);
            }
            status_ = QM_HANDLED();
            break;
        }
        /* @(/1/1/4/1/3/1) */
        case PLAYER_TRIGGER_SIG: {
            QACTIVE_POST((QActive *)&AO_Missile, MISSILE_FIRE_SIG,
                         (QParam)me->x
                         | (((QParam)(me->y - 1 + SHIP_HEIGHT) & 0xFF) << 8));
            status_ = QM_HANDLED();
            break;
        }
        /* @(/1/1/4/1/3/2) */
        case DESTROYED_MINE_SIG: {
            me->score += (uint16_t)Q_PAR(me);
            /* the score will be sent to the Tunnel by the next TIME_TICK */
            status_ = QM_HANDLED();
            break;
        }
        /* @(/1/1/4/1/3/3) */
        case HIT_WALL_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Ship_exploding_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Ship_exploding_s, &act_[0]);
            break;
        }
        /* @(/1/1/4/1/3/4) */
        case HIT_MINE_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Ship_exploding_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Ship_exploding_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/* @(/1/1/4/1/4) ...........................................................*/
static QState Ship_exploding_e(Ship * const me) {
    me->exp_ctr = 0;
    return QM_ENTRY(&Ship_exploding_s);
}
static QState Ship_exploding(Ship * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/1/4/1/4/0) */
        case TIME_TICK_SIG: {
            /* @(/1/1/4/1/4/0/0) */
            if (me->exp_ctr < 15) {
                ++me->exp_ctr;

                  /* tell the Tunnel to draw the current stage of Explosion */
                QACTIVE_POST((QActive *)&AO_Tunnel, EXPLOSION_SIG,
                         ((QParam)(EXPLOSION0_BMP + (me->exp_ctr >> 2)) << 16)
                         | (QParam)me->x
                         | (((QParam)(me->y - 4 + SHIP_HEIGHT) & 0xFF) << 8));
                status_ = QM_HANDLED();
            }
            /* @(/1/1/4/1/4/0/1) */
            else {
                QACTIVE_POST((QActive *)&AO_Tunnel, GAME_OVER_SIG, me->score);
                status_ = QM_TRAN(&Ship_parked_s, QMsm_emptyAction_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

