/*****************************************************************************
* Product: BSP for "Fly 'n' Shoot" game example, Win32
# Last updated for version 5.6.4
# Last updated on  2016-05-04
#
#                    Q u a n t u m     L e a P s
#                    ---------------------------
#                    innovating embedded systems
#
# Copyright (C) Quantum Leaps, LLC. All rights reserved.
#
# This program is open source software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Alternatively, this program may be distributed and modified under the
# terms of Quantum Leaps commercial licenses, which expressly supersede
# the GNU General Public License and are specifically designed for
# licensees interested in retaining the proprietary status of their code.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Contact information:
# http://www.state-machine.com
# mailto:info@state-machine.com
*****************************************************************************/
#include "qpn.h"
#include "game.h"
#include "bsp.h"

#include "qwin_gui.h" /* QWIN GUI */
#include "resource.h" /* GUI resource IDs generated by the resource editior */

#include <stdio.h>    /* for snprintf() */

Q_DEFINE_THIS_FILE

/* local variables ---------------------------------------------------------*/
static HINSTANCE l_hInst;   /* this application instance */
static HWND      l_hWnd;    /* main window handle */
static LPSTR     l_cmdLine; /* the command line string */

static GraphicDisplay   l_oled; /* the OLED display of the EK-LM3S811 board */
static SegmentDisplay   l_userLED;  /* USER LED of the EK-LM3S811 board */
static SegmentDisplay   l_scoreBoard; /* segment display for the score */
static OwnerDrawnButton l_userBtn; /* USER button of the EK-LM3S811 board */

/* (R,G,B) colors for the OLED display */
static BYTE const c_onColor [3] = { 255U, 255U, 255U }; /* white */
static BYTE const c_offColor[3] = {  15U,  15U,  15U }; /* very dark grey */

static BYTE l_ship_pos = GAME_SHIP_Y; /* the current ship Y-position */

/* Local functions ---------------------------------------------------------*/
static LRESULT CALLBACK WndProc(HWND hWnd, UINT iMsg,
                                WPARAM wParam, LPARAM lParam);

/*..........................................................................*/
static void playerTrigger(void) {
    QACTIVE_POST((QMActive *)&AO_Ship,   PLAYER_TRIGGER_SIG, 0U);
    QACTIVE_POST((QMActive *)&AO_Tunnel, PLAYER_TRIGGER_SIG, 0U);
}
/*..........................................................................*/
static void moveShipUp(void) {
    if (l_ship_pos > 0U) {
        --l_ship_pos;
    }
    QACTIVE_POST((QMActive *)&AO_Ship, PLAYER_SHIP_MOVE_SIG,
                 ((l_ship_pos << 8) | GAME_SHIP_X));
}
//............................................................................
static void moveShipDown(void) {
    if (l_ship_pos < (GAME_SCREEN_HEIGHT - 3U)) {
        ++l_ship_pos;
    }
    QACTIVE_POST((QMActive *)&AO_Ship, PLAYER_SHIP_MOVE_SIG,
                 ((l_ship_pos << 8) | GAME_SHIP_X));
}
/*..........................................................................*/
void terminate(int16_t result) {
    QF_stop(); /* stop the main QF application and the ticker thread */
    PostQuitMessage(result); /* post the Quit message to the GUI */

    GraphicDisplay_xtor(&l_oled);       /* cleanup the l_oled    resources */
    OwnerDrawnButton_xtor(&l_userBtn);  /* cleanup the l_userBtn resources */
    SegmentDisplay_xtor(&l_userLED);    /* cleanup the l_userLED resources */
    SegmentDisplay_xtor(&l_scoreBoard); /* cleanup the scoreBoard resources */
}
/*..........................................................................*/
/* thread function for running the application main_gui() */
static DWORD WINAPI appThread(LPVOID par) {
    (void)par; /* unused parameter */
    return (DWORD)main_gui(); /* run the QF-nano application */
}

/*--------------------------------------------------------------------------*/
int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrevInst,
                   LPSTR cmdLine, int iCmdShow)
{
    HWND hWnd;
    MSG  msg;

    (void)hPrevInst; /* unused parameter */

    l_hInst   = hInst;   /* save the application instance */
    l_cmdLine = cmdLine; /* save the command line string */

    /* create the main custom dialog window */
    hWnd = CreateCustDialog(hInst, IDD_APPLICATION, NULL,
                            &WndProc, "QP_APP");
    ShowWindow(hWnd, iCmdShow); /* show the main window */

    /* enter the message loop... */
    while (GetMessage(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    return msg.wParam;
}
/*..........................................................................*/
static LRESULT CALLBACK WndProc(HWND hWnd, UINT iMsg,
                                WPARAM wParam, LPARAM lParam)
{
    switch (iMsg) {

        /* Perform initialization upon cration of the main dialog window
        * NOTE: Any child-windows are NOT created yet at this time, so
        * the GetDlgItem() function can't be used (it will return NULL).
        */
        case WM_CREATE: {
            l_hWnd = hWnd; /* save the window handle */

            /* initialize the owner-drawn buttons...
            * NOTE: must be done *before* the first drawing of the buttons,
            * so WM_INITDIALOG is too late.
            */
            OwnerDrawnButton_init(&l_userBtn,
                       LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_BTN_UP)),
                       LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_BTN_DWN)),
                       LoadCursor(NULL, IDC_HAND));
            return 0;
        }

        /* Perform initialization after all child windows have been created */
        case WM_INITDIALOG: {
            GraphicDisplay_init(&l_oled,
                       BSP_SCREEN_WIDTH,  2U, /* scale horizontally by 2 */
                       BSP_SCREEN_HEIGHT, 2U, /* scale vertically by 2 */
                       GetDlgItem(hWnd, IDC_LCD), c_offColor);

            SegmentDisplay_init(&l_userLED,
                                1U,  /* 1 "segment" (the LED itself) */
                                2U); /* 2 bitmaps (for LED OFF/ON states) */
            SegmentDisplay_initSegment(&l_userLED,
                 0U, GetDlgItem(hWnd, IDC_LED));
            SegmentDisplay_initBitmap(&l_userLED,
                 0U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_LED_OFF)));
            SegmentDisplay_initBitmap(&l_userLED,
                 1U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_LED_ON)));

            SegmentDisplay_init(&l_scoreBoard,
                                4U,   /* 4 "segments" (digits 0-3) */
                                10U); /* 10 bitmaps (for 0-9 states) */
            SegmentDisplay_initSegment(&l_scoreBoard,
                 0U, GetDlgItem(hWnd, IDC_SEG0));
            SegmentDisplay_initSegment(&l_scoreBoard,
                 1U, GetDlgItem(hWnd, IDC_SEG1));
            SegmentDisplay_initSegment(&l_scoreBoard,
                 2U, GetDlgItem(hWnd, IDC_SEG2));
            SegmentDisplay_initSegment(&l_scoreBoard,
                 3U, GetDlgItem(hWnd, IDC_SEG3));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 0U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG0)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 1U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG1)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 2U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG2)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 3U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG3)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 4U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG4)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 5U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG5)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 6U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG6)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 7U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG7)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 8U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG8)));
            SegmentDisplay_initBitmap(&l_scoreBoard,
                 9U, LoadBitmap(l_hInst, MAKEINTRESOURCE(IDB_SEG9)));

            BSP_updateScore(0U);

            /* --> QP: spawn the application thread to run main() */
            Q_ALLEGE(CreateThread(NULL, 0, &appThread, NULL, 0, NULL)
                     != (HANDLE)0);
            return 0;
        }

        case WM_DESTROY: {
            terminate(0);
            return 0;
        }

        /* commands from regular buttons and menus... */
        case WM_COMMAND: {
            SetFocus(hWnd);
            switch (wParam) {
                case IDOK:
                case IDCANCEL: {
                    terminate(0);
                    break;
                }
            }
            return 0;
        }

        /* owner-drawn buttons... */
        case WM_DRAWITEM: {
            LPDRAWITEMSTRUCT pdis = (LPDRAWITEMSTRUCT)lParam;
            switch (pdis->CtlID) {
                case IDC_USER: {  /* USER owner-drawn button */
                    switch (OwnerDrawnButton_draw(&l_userBtn, pdis)) {
                        case BTN_DEPRESSED: {
                            playerTrigger();
                            SegmentDisplay_setSegment(&l_userLED, 0U, 1U);
                            break;
                        }
                        case BTN_RELEASED: {
                            SegmentDisplay_setSegment(&l_userLED, 0U, 0U);
                            break;
                        }
                        default: {
                            break;
                        }
                    }
                    break;
                }
            }
            return 0;
        }

        /* mouse input... */
        case WM_MOUSEWHEEL: {
            if ((HIWORD(wParam) & 0x8000U) == 0U) {/* wheel turned forward? */
                moveShipUp();
            }
            else { /* the wheel was turned backwards */
                moveShipDown();
            }
            return 0;
        }

        /* keyboard input... */
        case WM_KEYDOWN: {
            switch (wParam) {
                case VK_UP:
                    moveShipUp();
                    break;
                case VK_DOWN:
                    moveShipDown();
                    break;
                case VK_SPACE:
                    playerTrigger();
                    break;
            }
            return 0;
        }

    }
    return DefWindowProc(hWnd, iMsg, wParam, lParam) ;
}

/*--------------------------------------------------------------------------*/
void QF_onStartup(void) {
    QF_setTickRate(BSP_TICKS_PER_SEC); /* set the desired tick rate */
}
/*..........................................................................*/
void QF_onCleanup(void) {
}
/*..........................................................................*/
void QF_onClockTickISR(void) {
    QF_tickXISR(0U); /* perform the QF-nano clock tick processing */

    /* post TIME_TICK events to all interested active objects... */
    QACTIVE_POST_ISR((QMActive *)&AO_Tunnel,  TIME_TICK_SIG, 0U);
    QACTIVE_POST_ISR((QMActive *)&AO_Ship,    TIME_TICK_SIG, 0U);
    QACTIVE_POST_ISR((QMActive *)&AO_Missile, TIME_TICK_SIG, 0U);
}

/*..........................................................................*/
void Q_onAssert(char const Q_ROM * const file, int line) {
    char message[80];
    QF_stop(); /* stop the main QF application and the ticker thread */
    SNPRINTF_S(message, Q_DIM(message) - 1,
               "Assertion failed in module %s line %d", file, line);
    MessageBox(l_hWnd, message, "!!! ASSERTION !!!",
               MB_OK | MB_ICONEXCLAMATION | MB_APPLMODAL);
    PostQuitMessage(-1);
}

/*..........................................................................*/
void BSP_init(void) {
}
/*..........................................................................*/
void BSP_drawBitmap(uint8_t const *bitmap) {
    UINT x, y;
    /* map the EK-LM3S811 OLED pixels to the GraphicDisplay pixels... */
    for (y = 0; y < BSP_SCREEN_HEIGHT; ++y) {
        for (x = 0; x < BSP_SCREEN_WIDTH; ++x) {
            uint8_t bits = bitmap[x + (y/8U)*BSP_SCREEN_WIDTH];
            if ((bits & (1U << (y & 0x07U))) != 0U) {
                GraphicDisplay_setPixel(&l_oled, x, y, c_onColor);
            }
            else {
                GraphicDisplay_clearPixel(&l_oled, x, y);
            }
        }
    }
    GraphicDisplay_redraw(&l_oled); /* redraw the updated display */
}
/*..........................................................................*/
void BSP_drawNString(uint8_t x, uint8_t y, char const *str) {
    static uint8_t const font5x7[95][5] = {
        { 0x00U, 0x00U, 0x00U, 0x00U, 0x00U }, /* ' ' */
        { 0x00U, 0x00U, 0x4FU, 0x00U, 0x00U }, /* ! */
        { 0x00U, 0x07U, 0x00U, 0x07U, 0x00U }, /* " */
        { 0x14U, 0x7FU, 0x14U, 0x7FU, 0x14U }, /* # */
        { 0x24U, 0x2AU, 0x7FU, 0x2AU, 0x12U }, /* $ */
        { 0x23U, 0x13U, 0x08U, 0x64U, 0x62U }, /* % */
        { 0x36U, 0x49U, 0x55U, 0x22U, 0x50U }, /* & */
        { 0x00U, 0x05U, 0x03U, 0x00U, 0x00U }, /* ' */
        { 0x00U, 0x1CU, 0x22U, 0x41U, 0x00U }, /* ( */
        { 0x00U, 0x41U, 0x22U, 0x1CU, 0x00U }, /* ) */
        { 0x14U, 0x08U, 0x3EU, 0x08U, 0x14U }, /* * */
        { 0x08U, 0x08U, 0x3EU, 0x08U, 0x08U }, /* + */
        { 0x00U, 0x50U, 0x30U, 0x00U, 0x00U }, /* , */
        { 0x08U, 0x08U, 0x08U, 0x08U, 0x08U }, /* - */
        { 0x00U, 0x60U, 0x60U, 0x00U, 0x00U }, /* . */
        { 0x20U, 0x10U, 0x08U, 0x04U, 0x02U }, /* / */
        { 0x3EU, 0x51U, 0x49U, 0x45U, 0x3EU }, /* 0 */
        { 0x00U, 0x42U, 0x7FU, 0x40U, 0x00U }, /* 1 */
        { 0x42U, 0x61U, 0x51U, 0x49U, 0x46U }, /* 2 */
        { 0x21U, 0x41U, 0x45U, 0x4BU, 0x31U }, /* 3 */
        { 0x18U, 0x14U, 0x12U, 0x7FU, 0x10U }, /* 4 */
        { 0x27U, 0x45U, 0x45U, 0x45U, 0x39U }, /* 5 */
        { 0x3CU, 0x4AU, 0x49U, 0x49U, 0x30U }, /* 6 */
        { 0x01U, 0x71U, 0x09U, 0x05U, 0x03U }, /* 7 */
        { 0x36U, 0x49U, 0x49U, 0x49U, 0x36U }, /* 8 */
        { 0x06U, 0x49U, 0x49U, 0x29U, 0x1EU }, /* 9 */
        { 0x00U, 0x36U, 0x36U, 0x00U, 0x00U }, /* : */
        { 0x00U, 0x56U, 0x36U, 0x00U, 0x00U }, /* ; */
        { 0x08U, 0x14U, 0x22U, 0x41U, 0x00U }, /* < */
        { 0x14U, 0x14U, 0x14U, 0x14U, 0x14U }, /* = */
        { 0x00U, 0x41U, 0x22U, 0x14U, 0x08U }, /* > */
        { 0x02U, 0x01U, 0x51U, 0x09U, 0x06U }, /* ? */
        { 0x32U, 0x49U, 0x79U, 0x41U, 0x3EU }, /* @ */
        { 0x7EU, 0x11U, 0x11U, 0x11U, 0x7EU }, /* A */
        { 0x7FU, 0x49U, 0x49U, 0x49U, 0x36U }, /* B */
        { 0x3EU, 0x41U, 0x41U, 0x41U, 0x22U }, /* C */
        { 0x7FU, 0x41U, 0x41U, 0x22U, 0x1CU }, /* D */
        { 0x7FU, 0x49U, 0x49U, 0x49U, 0x41U }, /* E */
        { 0x7FU, 0x09U, 0x09U, 0x09U, 0x01U }, /* F */
        { 0x3EU, 0x41U, 0x49U, 0x49U, 0x7AU }, /* G */
        { 0x7FU, 0x08U, 0x08U, 0x08U, 0x7FU }, /* H */
        { 0x00U, 0x41U, 0x7FU, 0x41U, 0x00U }, /* I */
        { 0x20U, 0x40U, 0x41U, 0x3FU, 0x01U }, /* J */
        { 0x7FU, 0x08U, 0x14U, 0x22U, 0x41U }, /* K */
        { 0x7FU, 0x40U, 0x40U, 0x40U, 0x40U }, /* L */
        { 0x7FU, 0x02U, 0x0CU, 0x02U, 0x7FU }, /* M */
        { 0x7FU, 0x04U, 0x08U, 0x10U, 0x7FU }, /* N */
        { 0x3EU, 0x41U, 0x41U, 0x41U, 0x3EU }, /* O */
        { 0x7FU, 0x09U, 0x09U, 0x09U, 0x06U }, /* P */
        { 0x3EU, 0x41U, 0x51U, 0x21U, 0x5EU }, /* Q */
        { 0x7FU, 0x09U, 0x19U, 0x29U, 0x46U }, /* R */
        { 0x46U, 0x49U, 0x49U, 0x49U, 0x31U }, /* S */
        { 0x01U, 0x01U, 0x7FU, 0x01U, 0x01U }, /* T */
        { 0x3FU, 0x40U, 0x40U, 0x40U, 0x3FU }, /* U */
        { 0x1FU, 0x20U, 0x40U, 0x20U, 0x1FU }, /* V */
        { 0x3FU, 0x40U, 0x38U, 0x40U, 0x3FU }, /* W */
        { 0x63U, 0x14U, 0x08U, 0x14U, 0x63U }, /* X */
        { 0x07U, 0x08U, 0x70U, 0x08U, 0x07U }, /* Y */
        { 0x61U, 0x51U, 0x49U, 0x45U, 0x43U }, /* Z */
        { 0x00U, 0x7FU, 0x41U, 0x41U, 0x00U }, /* [ */
        { 0x02U, 0x04U, 0x08U, 0x10U, 0x20U }, /* \ */
        { 0x00U, 0x41U, 0x41U, 0x7FU, 0x00U }, /* ] */
        { 0x04U, 0x02U, 0x01U, 0x02U, 0x04U }, /* ^ */
        { 0x40U, 0x40U, 0x40U, 0x40U, 0x40U }, /* _ */
        { 0x00U, 0x01U, 0x02U, 0x04U, 0x00U }, /* ` */
        { 0x20U, 0x54U, 0x54U, 0x54U, 0x78U }, /* a */
        { 0x7FU, 0x48U, 0x44U, 0x44U, 0x38U }, /* b */
        { 0x38U, 0x44U, 0x44U, 0x44U, 0x20U }, /* c */
        { 0x38U, 0x44U, 0x44U, 0x48U, 0x7FU }, /* d */
        { 0x38U, 0x54U, 0x54U, 0x54U, 0x18U }, /* e */
        { 0x08U, 0x7EU, 0x09U, 0x01U, 0x02U }, /* f */
        { 0x0CU, 0x52U, 0x52U, 0x52U, 0x3EU }, /* g */
        { 0x7FU, 0x08U, 0x04U, 0x04U, 0x78U }, /* h */
        { 0x00U, 0x44U, 0x7DU, 0x40U, 0x00U }, /* i */
        { 0x20U, 0x40U, 0x44U, 0x3DU, 0x00U }, /* j */
        { 0x7FU, 0x10U, 0x28U, 0x44U, 0x00U }, /* k */
        { 0x00U, 0x41U, 0x7FU, 0x40U, 0x00U }, /* l */
        { 0x7CU, 0x04U, 0x18U, 0x04U, 0x78U }, /* m */
        { 0x7CU, 0x08U, 0x04U, 0x04U, 0x78U }, /* n */
        { 0x38U, 0x44U, 0x44U, 0x44U, 0x38U }, /* o */
        { 0x7CU, 0x14U, 0x14U, 0x14U, 0x08U }, /* p */
        { 0x08U, 0x14U, 0x14U, 0x18U, 0x7CU }, /* q */
        { 0x7CU, 0x08U, 0x04U, 0x04U, 0x08U }, /* r */
        { 0x48U, 0x54U, 0x54U, 0x54U, 0x20U }, /* s */
        { 0x04U, 0x3FU, 0x44U, 0x40U, 0x20U }, /* t */
        { 0x3CU, 0x40U, 0x40U, 0x20U, 0x7CU }, /* u */
        { 0x1CU, 0x20U, 0x40U, 0x20U, 0x1CU }, /* v */
        { 0x3CU, 0x40U, 0x30U, 0x40U, 0x3CU }, /* w */
        { 0x44U, 0x28U, 0x10U, 0x28U, 0x44U }, /* x */
        { 0x0CU, 0x50U, 0x50U, 0x50U, 0x3CU }, /* y */
        { 0x44U, 0x64U, 0x54U, 0x4CU, 0x44U }, /* z */
        { 0x00U, 0x08U, 0x36U, 0x41U, 0x00U }, /* { */
        { 0x00U, 0x00U, 0x7FU, 0x00U, 0x00U }, /* | */
        { 0x00U, 0x41U, 0x36U, 0x08U, 0x00U }, /* } */
        { 0x02U, 0x01U, 0x02U, 0x04U, 0x02U }, /* ~ */
    };
    UINT dx, dy;

    while (*str != '\0') {
        uint8_t const *ch = &font5x7[*str - ' '][0];
        for (dx = 0U; dx < 5U; ++dx) {
            for (dy = 0U; dy < 8U; ++dy) {
                if ((ch[dx] & (1U << dy)) != 0U) {
                    GraphicDisplay_setPixel(&l_oled, (UINT)(x + dx),
                                         (UINT)(y*8U + dy), c_onColor);
                }
                else {
                    GraphicDisplay_clearPixel(&l_oled, (UINT)(x + dx),
                                           (UINT)(y*8U + dy));
                }
            }
        }
        ++str;
        x += 6;
    }
    GraphicDisplay_redraw(&l_oled); /* redraw the updated display */
}
/*..........................................................................*/
void BSP_updateScore(uint16_t score) {
    /* update the score in the l_scoreBoard SegmentDisplay */
    SegmentDisplay_setSegment(&l_scoreBoard, 0U, (UINT)(score % 10U));
    score /= 10U;
    SegmentDisplay_setSegment(&l_scoreBoard, 1U, (UINT)(score % 10U));
    score /= 10U;
    SegmentDisplay_setSegment(&l_scoreBoard, 2U, (UINT)(score % 10U));
    score /= 10U;
    SegmentDisplay_setSegment(&l_scoreBoard, 3U, (UINT)(score % 10U));
}
/*..........................................................................*/
void BSP_displayOn(void) {
    SegmentDisplay_setSegment(&l_userLED, 0U, 1U);
}
/*..........................................................................*/
void BSP_displayOff(void) {
    SegmentDisplay_setSegment(&l_userLED, 0U, 0U);
    GraphicDisplay_clear(&l_oled);
    GraphicDisplay_redraw(&l_oled);
}
