/*****************************************************************************
* Model: pelican.qm
* File:  ./pelican.h
*
* This file has been generated automatically by QP Modeler (QM).
* DO NOT EDIT THIS FILE MANUALLY.
*
* Please visit www.state-machine.com/qm for more information.
*****************************************************************************/
#ifndef pelican_h
#define pelican_h

enum PelicanSignals {
    PEDS_WAITING_SIG = Q_USER_SIG,
    OFF_SIG,
    ON_SIG,
    TEST_SIG
};

// active objects ................................................*/
/* @(/1/3) .................................................................*/
/** 
* constructor
*/
void Pelican_ctor(void);

/* @(/1/4) .................................................................*/
/** 
* constructor
*/
void Ped_ctor(void);


extern struct PelicanTag AO_Pelican;
extern struct PedTag     AO_Ped;

#endif /* pelican_h */
